### ISSUE TITLE
is there any article/video explaining the development process?

### ISSUE THREAD

**Issue by borsemayur2** [abdelhamidbakhta/token-vesting-contracts#2]
I'm trying to create token vesting contract where the admin can distribute the token to given addresses (eg. 5) evenly for 12 months with per minute release schedule. What modifications will be needed etc.

**Comment by abdelhamidbakhta** [comment]
No modification needed. This smart contract can handle this use case. Unfortunately there is no video or article.

**Comment by borsemayur2** [comment]
Thanks
