### ISSUE TITLE
Error with yarn test

### ISSUE THREAD

**Issue by joelamouche** [abdelhamidbakhta/token-vesting-contracts#35]
After running yarn, I get this error when running yarn test:

```
➜  token-vesting-contracts git:(main) ✗ yarn test
yarn run v1.22.10
$ npx hardhat test --logs
Error HH404: File lib/solmate/src/tokens/ERC20.sol, imported from src/TokenVesting.sol, not found.

For more info go to https://hardhat.org/HH404 or run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Comment by abdelhamidbakhta** [comment]
> After running yarn, I get this error when running yarn test:
> 
> ```
> ➜  token-vesting-contracts git:(main) ✗ yarn test
> yarn run v1.22.10
> $ npx hardhat test --logs
> Error HH404: File lib/solmate/src/tokens/ERC20.sol, imported from src/TokenVesting.sol, not found.
> 
> For more info go to https://hardhat.org/HH404 or run Hardhat with --show-stack-traces
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

the `forge build` command works for you ?

**Comment by joelamouche** [comment]
Unrelated question but have you thought of adding the feature of handling multiple beneficiaries by having a list of beneficiaries instead of one beneficiary?

**Comment by abdelhamidbakhta** [comment]
> Sorry, I meant to say I did NOT install foundry 😖 Since the documentation implies that the repo can be used with hardhat without foundry. Trying with foundry now... The tests do work after running allthe foundry commands. Maybe you should specify it is necessary in the readme...

Oh ok. Yeah it should be more explicit indeed. Feel free to submit a PR if you want ;)

**Comment by abdelhamidbakhta** [comment]
> Unrelated question but have you thought of adding the feature of handling multiple beneficiaries by having a list of beneficiaries instead of one beneficiary?

That's a good feature request. Can you please describe it in an issue ?

**Comment by joelamouche** [comment]
Sounds good I will make a PR and an issue later today

**Comment by abdelhamidbakhta** [comment]
> Sounds good I will make a PR and an issue later today

awesome thanks
