### ISSUE TITLE
Non-linear Vesting

### ISSUE THREAD

**Issue by jeromevvb** [abdelhamidbakhta/token-vesting-contracts#8]
Hi @abdelhamidbakhta 

Thank you so much for your work.
How can i handle the case of non-linear vesting?

For example, i have 3 months vesting.
First month i want to release 25%
the second month 25%
and the third 50%.

How this can be achieve here?
Thank you so much.

**Comment by abdelhamidbakhta** [comment]
> Hi @abdelhamidbakhta
> 
> Thank you so much for your work. How can i handle the case of non-linear vesting?
> 
> For example, i have 3 months vesting. First month i want to release 25% the second month 25% and the third 50%.
> 
> How this can be achieve here? Thank you so much.

This can be done with 3 vesting schedules. One for each month with a one month period. You can create a vesting for the first month with 25%. Another vesting starting after one month and the third vesting starting after two months.

**Comment by jeromevvb** [comment]
Thank you @abdelhamidbakhta 
Another question:
If i want to create multiple vesting schedule in one transaction, would you recommend to use an array of `_beneficiary` in the `createVestingSchedule` and loop into it?

What would be the best approach? And gaz efficient?
